#ifndef LIBUSRPLATFORM_GLOBAL_H
#define LIBUSRPLATFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBUSRPLATFORM_LIBRARY)
#  define LIBUSRPLATFORM_EXPORT Q_DECL_EXPORT
#else
#  define LIBUSRPLATFORM_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBUSRPLATFORM_GLOBAL_H
