#ifndef USRPLATFORM_GLOBAL_H
#define USRPLATFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USRPLATFORM_LIBRARY)
#  define USRPLATFORMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define USRPLATFORMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USRPLATFORM_GLOBAL_H
